### ISSUE TITLE
Error in plotting stacks-day output

### ISSUE THREAD

**Issue by cmbarton** [ahb108/rcarbon#60] opened 2022-06-25 00:29 UTC
I've created a stacked spd and want to plot it. The code to create the object runs fine with no errors. But when I try to plot it, I get the following error (same with all plot types). 

```
> plot(stacked.spd, type = "multipanel")

Error in PrDens[, i] <- x$spds[[i]][[2]][[2]] : 
  number of items to replace is not a multiple of replacement length
```
I've tried a number of things and nothing seems to work. There are 6 groups. Is that a problem?

**Comment by ercrema** [comment] 2022-06-25 06:22
The number of groups shouldn't be a problem. But I need to have more details to replicate your error in order to help. Can you give us the full script? Ideally with the actual data you've used?

**Comment by ercrema** [comment] 2022-06-25 17:44
Alternatively could you share with the printout of the following commands? (assuming `stacked.spd` was the output from `stackspd()`)
```
stacked.spd$metadata
length(stacked.spd$spds)
lapply(stacked.spd$spds,function(x){dim(x[[2]])})
```

**Comment by cmbarton** [comment] 2022-06-25 17:56
Thanks Enrico. Here is the script to create the stackspd. I'm attaching an RDA file that is the data set. This is a subset of a larger dataset that has run without problem with calibrate, modeltest, and permtest.

```
c14dates.industry.group <- c14dates %>% 
  dplyr::filter(!is.na(industry.group))

date.bins <-  c14dates.industry.group %>% 
  with(., binPrep(site, C14.mean, 100))

stacked.spd <- c14dates.industry.group %>% 
  with(., calibrate(x=C14.mean, errors=C14.SD, calCurves = calib.curve, normalised=TRUE, calMatrix=FALSE)) %>% 
  stackspd(timeRange=c(35000,8000), 
           bins=date.bins,
           group=c14dates.industry.group$industry.group, 
           runm = 500, 
           datenormalised=TRUE)
```

[dates_industry_group.csv](https://github.com/ahb108/rcarbon/files/8985316/dates_industry_group.csv)

**Comment by ercrema** [comment] 2022-06-25 18:50
Thanks Mike - I think the problem is with the underlying `spd()` function. Somehow setting datenormalised = TRUE overrides the user-defined timeRange. When the dates are already normalised, there is actually no need to specify this again in `spd()` (see below for an example). The code below should fix your problem: 

```
c14dates.industry.group <- c14dates %>% 
  dplyr::filter(!is.na(industry.group))

date.bins <-  c14dates.industry.group %>% 
  with(., binPrep(site, C14.mean, 100))

stacked.spd <- c14dates.industry.group %>% 
  with(., calibrate(x=C14.mean, errors=C14.SD, calCurves = calib.curve, normalised=TRUE, calMatrix=FALSE)) %>% 
  stackspd(timeRange=c(35000,8000), 
           bins=date.bins,
           group=c14dates.industry.group$industry.group, 
           runm = 500)


```
@ahb108 - I think we need to check sdp() when datenormalised=TRUE. See example below for the problem. Any reason why the actual timeRange is reduced?

```
library(rcarbon)
data(euroevol)
DK=subset(euroevol,Country=="Denmark") #subset of Danish dates
x1=calibrate(x=DK$C14Age,errors=DK$C14SD,calCurves='intcal20',normalised=TRUE)
x2=calibrate(x=DK$C14Age,errors=DK$C14SD,calCurves='intcal20',normalised=FALSE)

par(mfrow=c(2,2))
plot(spd(x1,timeRange=c(20000,2000),datenormalised=TRUE))
plot(spd(x1,timeRange=c(20000,2000),datenormalised=FALSE))
plot(spd(x2,timeRange=c(20000,2000),datenormalised=TRUE))
plot(spd(x2,timeRange=c(20000,2000),datenormalised=FALSE))
```
![image](https://user-images.githubusercontent.com/2821047/175786721-92bcbac7-4ca0-4dc5-9efe-e9e5ed1d1b13.png)

**Comment by ercrema** [comment] 2022-06-25 20:31
closing this issue and migrating the problem on spd on #61

**Closed as completed by ercrema** 2022-06-25 20:31 UTC
Labels: bug

**Comment by cmbarton** [comment] 2022-06-26 22:30
> Any reason why the actual timeRange is reduced?

Is this question for me? If so, I don't understand it.

**Comment by ercrema** [comment] 2022-06-27 05:40
The question was for Andy. It was designed to handle the opposite situation when the timeRange was narrower than the supplied date range. This caused problems for normalising the dates but was also inadvertently overriding the - display timeRange. Anyway, your code should work with the fix above or as it is if you install and use the GitHub version of rcarbon (rather the CRAN one). I will update the CRAN one sometime this week.

**Comment by ahb108** [comment] 2022-06-27 09:12
Yes, nice fix I think. Thanks for mentioning it @cmbarton

**Comment by cmbarton** [comment] 2022-06-27 17:19
Thanks much folks. I'll install it from GitHub today and try it out.

**Comment by cmbarton** [comment] 2022-06-27 17:29
I don't know whether to put this here and reopen, in #61, or make a new issue. 

I just installed rcarbon from GitHub. It installed fine, but I get an error trying to load it. 

```
Warning in split_lines(text) :
  restarting interrupted promise evaluation
Warning in split_lines(text) : internal error -3 in R_decompress1
Error in split_lines(text) : 
  lazy-load database '/Users/cmbarton/Library/R/4.1/library/xfun/R/xfun.rdb' is corrupt
Warning in eval(parse_only(paste("alist(", quote_label(params), ")"))) :
  restarting interrupted promise evaluation
Warning in eval(parse_only(paste("alist(", quote_label(params), ")"))) :
  internal error -3 in R_decompress1
(*) NOTE: I saw chunk options " setup, include=FALSE"
 please go to https://yihui.org/knitr/options
 (it is likely that you forgot to quote "character" options)
```

**Comment by ercrema** [comment] 2022-06-27 20:05
This doesn't happen on my machine and I'm not sure if it specific to rcarbon. The error seem to be pointing to xfun which reverse depends on knitr, which is one of rcarbon's dependencies. Would try re-installing knitr, but hard to help as I cannot reproduce the error.

**Comment by cmbarton** [comment] 2022-06-27 20:44
I updated all to v. 4.2 and all packages. Now I don't get the error either. Everything works great. Thanks.
